#!/bin/bash
# SPDX-FileCopyrightText: 2026 Tom Haynes <loghyr@gmail.com>
# SPDX-License-Identifier: BSD-2-Clause OR GPL-2.0-only
#
# FS QA Test No. 901
#
# cthon26/nfsv42-tests: op_allocate
#
# posix_fallocate -> NFSv4.2 ALLOCATE (RFC 7862 S4).  Writes up to
# 4 MiB, hence not tagged quick.
#
. ./common/preamble
_begin_fstest auto nfs

_cleanup()
{
	cd /
	rm -rf $tmp.*
}

. ./common/filter
. ./common/cthon26

_supported_fs nfs
_require_test
_require_cthon26_binary op_allocate

_cthon26_run op_allocate

status=0
exit
