#!/bin/bash
# SPDX-FileCopyrightText: 2026 Tom Haynes <loghyr@gmail.com>
# SPDX-License-Identifier: BSD-2-Clause OR GPL-2.0-only
#
# FS QA Test No. 902
#
# cthon26/nfsv42-tests: op_change_attr
#
# statx(STATX_CHANGE_COOKIE) -> NFSv4 change attribute (RFC 7530
# S5.8.1.4).  Requires Linux 6.5+ kernel and matching glibc; skips
# otherwise.
#
. ./common/preamble
_begin_fstest auto nfs quick cthon26

_cleanup()
{
	cd /
	rm -rf $tmp.*
}

. ./common/filter
. ./common/cthon26

_require_test
_require_cthon26_binary op_change_attr

_cthon26_run op_change_attr

status=0
exit
