#!/bin/bash
# SPDX-FileCopyrightText: 2026 Tom Haynes <loghyr@gmail.com>
# SPDX-License-Identifier: BSD-2-Clause OR GPL-2.0-only
#
# FS QA Test No. 903
#
# cthon26/nfsv42-tests: op_clone
#
# ioctl(FICLONE) -> NFSv4.2 CLONE (RFC 7862 S11).  Requires a reflink-
# capable backing filesystem on the server; skips otherwise.
#
. ./common/preamble
_begin_fstest auto nfs

_cleanup()
{
	cd /
	rm -rf $tmp.*
}

. ./common/filter
. ./common/cthon26

_supported_fs nfs
_require_test
_require_cthon26_binary op_clone

_cthon26_run op_clone

status=0
exit
