#!/bin/bash
# SPDX-FileCopyrightText: 2026 Tom Haynes <loghyr@gmail.com>
# SPDX-License-Identifier: BSD-2-Clause OR GPL-2.0-only
#
# FS QA Test No. 908
#
# cthon26/nfsv42-tests: op_deleg_read
#
# NFSv4 read delegation + CB_RECALL on conflicting write (RFC 7530
# S10.4.2).  Cross-client cases 2 and 3 are skipped without -S SERVER;
# the local shared-read case always runs.
#
. ./common/preamble
_begin_fstest auto nfs quick cthon26

_cleanup()
{
	cd /
	rm -rf $tmp.*
}

. ./common/filter
. ./common/cthon26

_supported_fs nfs
_require_test
_require_cthon26_binary op_deleg_read

_cthon26_run op_deleg_read

status=0
exit
