#!/bin/bash
# SPDX-FileCopyrightText: 2026 Tom Haynes <loghyr@gmail.com>
# SPDX-License-Identifier: BSD-2-Clause OR GPL-2.0-only
#
# FS QA Test No. 910
#
# cthon26/nfsv42-tests: op_io_advise
#
# posix_fadvise(2) -> NFSv4.2 IO_ADVISE (RFC 7862 S5).
#
. ./common/preamble
_begin_fstest auto nfs quick cthon26

_cleanup()
{
	cd /
	rm -rf $tmp.*
}

. ./common/filter
. ./common/cthon26

_supported_fs nfs
_require_test
_require_cthon26_binary op_io_advise

_cthon26_run op_io_advise

status=0
exit
