#!/bin/bash
# SPDX-FileCopyrightText: 2026 Tom Haynes <loghyr@gmail.com>
# SPDX-License-Identifier: BSD-2-Clause OR GPL-2.0-only
#
# FS QA Test No. 915
#
# cthon26/nfsv42-tests: op_open_excl
#
# O_CREAT|O_EXCL -> NFSv4 OPEN createmode=EXCLUSIVE4_1 (RFC 7530
# S18.16).
#
. ./common/preamble
_begin_fstest auto nfs quick cthon26

_cleanup()
{
	cd /
	rm -rf $tmp.*
}

. ./common/filter
. ./common/cthon26

_supported_fs nfs
_require_test
_require_cthon26_binary op_open_excl

_cthon26_run op_open_excl

status=0
exit
