#!/bin/bash
# SPDX-FileCopyrightText: 2026 Tom Haynes <loghyr@gmail.com>
# SPDX-License-Identifier: BSD-2-Clause OR GPL-2.0-only
#
# FS QA Test No. 918
#
# cthon26/nfsv42-tests: op_readdir_many
#
# 1024-entry READDIR cookie/continuation stress (RFC 7530 S18.23).
# Creates many files, hence not tagged quick.
#
. ./common/preamble
_begin_fstest auto nfs

_cleanup()
{
	cd /
	rm -rf $tmp.*
}

. ./common/filter
. ./common/cthon26

_supported_fs nfs
_require_test
_require_cthon26_binary op_readdir_many

_cthon26_run op_readdir_many

status=0
exit
