#!/bin/bash
# SPDX-FileCopyrightText: 2026 Tom Haynes <loghyr@gmail.com>
# SPDX-License-Identifier: BSD-2-Clause OR GPL-2.0-only
#
# FS QA Test No. 921
#
# cthon26/nfsv42-tests: op_seek
#
# lseek(SEEK_HOLE/SEEK_DATA) -> NFSv4.2 SEEK + READ_PLUS.  Linux /
# FreeBSD / macOS 10.15+; skips on platforms without SEEK_HOLE.
#
. ./common/preamble
_begin_fstest auto nfs quick

_cleanup()
{
	cd /
	rm -rf $tmp.*
}

. ./common/filter
. ./common/cthon26

_supported_fs nfs
_require_test
_require_cthon26_binary op_seek

_cthon26_run op_seek

status=0
exit
