#!/bin/bash
# SPDX-FileCopyrightText: 2026 Tom Haynes <loghyr@gmail.com>
# SPDX-License-Identifier: BSD-2-Clause OR GPL-2.0-only
#
# FS QA Test No. 922
#
# cthon26/nfsv42-tests: op_server_caps
#
# EXCHANGE_ID / SECINFO_NO_NAME against an NFSv4.1 server (RFC 5661).
# Requires CTHON26_NFS_SERVER in the environment; skips otherwise.
#
. ./common/preamble
_begin_fstest auto nfs quick

_cleanup()
{
	cd /
	rm -rf $tmp.*
}

. ./common/filter
. ./common/cthon26

_supported_fs nfs
_require_test
_require_cthon26_binary op_server_caps

# op_server_caps needs -S SERVER; use CTHON26_NFS_SERVER if set.
if [ -n "${CTHON26_NFS_SERVER:-}" ]; then
	_cthon26_run_args op_server_caps -S "$CTHON26_NFS_SERVER"
else
	_notrun "op_server_caps needs -S SERVER; set CTHON26_NFS_SERVER to the NFS server hostname"
fi

status=0
exit
