#!/bin/bash
# SPDX-FileCopyrightText: 2026 Tom Haynes <loghyr@gmail.com>
# SPDX-License-Identifier: BSD-2-Clause OR GPL-2.0-only
#
# FS QA Test No. 923
#
# cthon26/nfsv42-tests: op_setattr
#
# chmod/chown/truncate/utimensat -> NFSv4 SETATTR (RFC 7530 S18.30).
# case_chown_noop emits a NOTE rather than failing on servers with
# idmap mismatch.
#
. ./common/preamble
_begin_fstest auto nfs quick

_cleanup()
{
	cd /
	rm -rf $tmp.*
}

. ./common/filter
. ./common/cthon26

_supported_fs nfs
_require_test
_require_cthon26_binary op_setattr

_cthon26_run op_setattr

status=0
exit
