#!/bin/bash
# SPDX-FileCopyrightText: 2026 Tom Haynes <loghyr@gmail.com>
# SPDX-License-Identifier: BSD-2-Clause OR GPL-2.0-only
#
# FS QA Test No. 934
#
# cthon26/nfsv42-tests: op_open_downgrade
#
# open/close combinations -> NFSv4 OPEN_DOWNGRADE (RFC 7530 S18.18).
#
. ./common/preamble
_begin_fstest auto nfs quick cthon26

_cleanup()
{
	cd /
	rm -rf $tmp.*
}

. ./common/filter
. ./common/cthon26

_require_test
_require_cthon26_binary op_open_downgrade

_cthon26_run op_open_downgrade

status=0
exit
