#!/bin/bash
# SPDX-FileCopyrightText: 2026 Tom Haynes <loghyr@gmail.com>
# SPDX-License-Identifier: BSD-2-Clause OR GPL-2.0-only
#
# FS QA Test No. 940
#
# cthon26/nfsv42-tests: op_symlink_nofollow
#
# AT_SYMLINK_NOFOLLOW / O_NOFOLLOW across *at() syscalls (POSIX.1-2008).
#
. ./common/preamble
_begin_fstest auto nfs quick cthon26

_cleanup()
{
	cd /
	rm -rf $tmp.*
}

. ./common/filter
. ./common/cthon26

_require_test
_require_cthon26_binary op_symlink_nofollow

_cthon26_run op_symlink_nofollow

status=0
exit
