#!/bin/bash
# SPDX-FileCopyrightText: 2026 Tom Haynes <loghyr@gmail.com>
# SPDX-License-Identifier: BSD-2-Clause OR GPL-2.0-only
#
# FS QA Test No. 900
#
# nfs-conformance: op_access
#
# Exercises NFSv4 ACCESS (RFC 7530 S18.1) through the access(2) and
# faccessat(2) POSIX surface.  Delegates to the nfs-conformance op_access
# binary; see nfs-conformance/op_access.c for the per-case details.
#
. ./common/preamble
_begin_fstest auto nfs quick nfs-conformance

_cleanup()
{
	cd /
	rm -rf $tmp.*
}

. ./common/filter
. ./common/nfs-conformance

_require_test
_require_nfs_conformance_binary op_access

_nfs_conformance_run op_access

status=0
exit
