#!/bin/bash
# SPDX-FileCopyrightText: 2026 Tom Haynes <loghyr@gmail.com>
# SPDX-License-Identifier: BSD-2-Clause OR GPL-2.0-only
#
# FS QA Test No. 912
#
# nfs-conformance: op_mkdir
#
# mkdir/mkdirat -> NFSv4 CREATE(NF4DIR) (RFC 7530 S18.4).
#
. ./common/preamble
_begin_fstest auto nfs quick nfs-conformance

_cleanup()
{
	cd /
	rm -rf $tmp.*
}

. ./common/filter
. ./common/nfs-conformance

_require_test
_require_nfs_conformance_binary op_mkdir

_nfs_conformance_run op_mkdir

status=0
exit
