#!/bin/bash
# SPDX-FileCopyrightText: 2026 Tom Haynes <loghyr@gmail.com>
# SPDX-License-Identifier: BSD-2-Clause OR GPL-2.0-only
#
# FS QA Test No. 915
#
# nfs-conformance: op_open_excl
#
# O_CREAT|O_EXCL -> NFSv4 OPEN createmode=EXCLUSIVE4_1 (RFC 7530
# S18.16).
#
. ./common/preamble
_begin_fstest auto nfs quick nfs-conformance

_cleanup()
{
	cd /
	rm -rf $tmp.*
}

. ./common/filter
. ./common/nfs-conformance

_require_test
_require_nfs_conformance_binary op_open_excl

_nfs_conformance_run op_open_excl

status=0
exit
