#!/bin/bash
# SPDX-FileCopyrightText: 2026 Tom Haynes <loghyr@gmail.com>
# SPDX-License-Identifier: BSD-2-Clause OR GPL-2.0-only
#
# FS QA Test No. 916
#
# nfs-conformance: op_read_plus_sparse
#
# pread over holes -> NFSv4.2 READ_PLUS (RFC 7862 S15).
#
. ./common/preamble
_begin_fstest auto nfs quick nfs-conformance

_cleanup()
{
	cd /
	rm -rf $tmp.*
}

. ./common/filter
. ./common/nfs-conformance

_require_test
_require_nfs_conformance_binary op_read_plus_sparse

_nfs_conformance_run op_read_plus_sparse

status=0
exit
