#!/bin/bash
# SPDX-FileCopyrightText: 2026 Tom Haynes <loghyr@gmail.com>
# SPDX-License-Identifier: BSD-2-Clause OR GPL-2.0-only
#
# FS QA Test No. 926
#
# nfs-conformance: op_truncate_grow
#
# ftruncate extending a file -> NFSv4 SETATTR(size) with sparse hole
# (RFC 7530 S5.8.1.5).
#
. ./common/preamble
_begin_fstest auto nfs quick nfs-conformance

_cleanup()
{
	cd /
	rm -rf $tmp.*
}

. ./common/filter
. ./common/nfs-conformance

_require_test
_require_nfs_conformance_binary op_truncate_grow

_nfs_conformance_run op_truncate_grow

status=0
exit
