#!/bin/bash
# SPDX-FileCopyrightText: 2026 Tom Haynes <loghyr@gmail.com>
# SPDX-License-Identifier: BSD-2-Clause OR GPL-2.0-only
#
# FS QA Test No. 927
#
# cthon26/nfsv42-tests: op_unicode_names
#
# UTF-8 filenames (Latin-1 / CJK / emoji) -> NFSv4 name encoding
# (RFC 7530 S1.4.2).
#
. ./common/preamble
_begin_fstest auto nfs quick cthon26

_cleanup()
{
	cd /
	rm -rf $tmp.*
}

. ./common/filter
. ./common/cthon26

_require_test
_require_cthon26_binary op_unicode_names

_cthon26_run op_unicode_names

status=0
exit
