#!/bin/bash
# SPDX-FileCopyrightText: 2026 Tom Haynes <loghyr@gmail.com>
# SPDX-License-Identifier: BSD-2-Clause OR GPL-2.0-only
#
# FS QA Test No. 928
#
# nfs-conformance: op_xattr
#
# setxattr/getxattr/listxattr/removexattr on user.* namespace ->
# NFSv4.2 XATTR ops (RFC 8276).  Skips on servers / backends that
# do not support user.* xattrs.
#
. ./common/preamble
_begin_fstest auto nfs nfs-conformance

_cleanup()
{
	cd /
	rm -rf $tmp.*
}

. ./common/filter
. ./common/nfs-conformance

_require_test
_require_nfs_conformance_binary op_xattr

_nfs_conformance_run op_xattr

status=0
exit
