#!/bin/bash
# SPDX-FileCopyrightText: 2026 Tom Haynes <loghyr@gmail.com>
# SPDX-License-Identifier: BSD-2-Clause OR GPL-2.0-only
#
# FS QA Test No. 929
#
# nfs-conformance: op_lookup
#
# open/stat -> NFSv4 LOOKUP/LOOKUPP (RFC 7530 S18.14/S18.15).
#
. ./common/preamble
_begin_fstest auto nfs quick nfs-conformance

_cleanup()
{
	cd /
	rm -rf $tmp.*
}

. ./common/filter
. ./common/nfs-conformance

_require_test
_require_nfs_conformance_binary op_lookup

_nfs_conformance_run op_lookup

status=0
exit
