#!/bin/bash
# SPDX-FileCopyrightText: 2026 Tom Haynes <loghyr@gmail.com>
# SPDX-License-Identifier: BSD-2-Clause OR GPL-2.0-only
#
# FS QA Test No. 931
#
# nfs-conformance: op_delegation_write
#
# open/write/close -> NFSv4 OPEN_DELEGATE_WRITE (RFC 8881 S10.4).
#
. ./common/preamble
_begin_fstest auto nfs nfs-conformance

_cleanup()
{
	cd /
	rm -rf $tmp.*
}

. ./common/filter
. ./common/nfs-conformance

_require_test
_require_nfs_conformance_binary op_delegation_write

_nfs_conformance_run op_delegation_write

status=0
exit
