#!/bin/bash
# SPDX-FileCopyrightText: 2026 Tom Haynes <loghyr@gmail.com>
# SPDX-License-Identifier: BSD-2-Clause OR GPL-2.0-only
#
# FS QA Test No. 934
#
# nfs-conformance: op_open_downgrade
#
# open/close combinations -> NFSv4 OPEN_DOWNGRADE (RFC 7530 S18.18).
#
. ./common/preamble
_begin_fstest auto nfs quick nfs-conformance

_cleanup()
{
	cd /
	rm -rf $tmp.*
}

. ./common/filter
. ./common/nfs-conformance

_require_test
_require_nfs_conformance_binary op_open_downgrade

_nfs_conformance_run op_open_downgrade

status=0
exit
