#!/bin/bash
# SPDX-FileCopyrightText: 2026 Tom Haynes <loghyr@gmail.com>
# SPDX-License-Identifier: BSD-2-Clause OR GPL-2.0-only
#
# FS QA Test No. 935
#
# nfs-conformance: op_owner_override
#
# Linux owner-override semantics beyond strict POSIX: chmod/unlink/rename
# on read-only files owned by the caller.  Exercises the NFS server paths
# that git gc, editors, and package managers rely on.
#
. ./common/preamble
_begin_fstest auto nfs quick nfs-conformance

_cleanup()
{
	cd /
	rm -rf $tmp.*
}

. ./common/filter
. ./common/nfs-conformance

_require_test
_require_nfs_conformance_binary op_owner_override

_nfs_conformance_run op_owner_override

status=0
exit
