#!/bin/bash
# SPDX-FileCopyrightText: 2026 Tom Haynes <loghyr@gmail.com>
# SPDX-License-Identifier: BSD-2-Clause OR GPL-2.0-only
#
# FS QA Test No. 940
#
# nfs-conformance: op_symlink_nofollow
#
# AT_SYMLINK_NOFOLLOW / O_NOFOLLOW across *at() syscalls (POSIX.1-2008).
#
. ./common/preamble
_begin_fstest auto nfs quick nfs-conformance

_cleanup()
{
	cd /
	rm -rf $tmp.*
}

. ./common/filter
. ./common/nfs-conformance

_require_test
_require_nfs_conformance_binary op_symlink_nofollow

_nfs_conformance_run op_symlink_nofollow

status=0
exit
