#!/bin/bash
# SPDX-FileCopyrightText: 2026 Tom Haynes <loghyr@gmail.com>
# SPDX-License-Identifier: BSD-2-Clause OR GPL-2.0-only
#
# FS QA Test No. 941
#
# nfs-conformance: op_rename_self
#
# rename() same-file edge cases (POSIX.1-2024 clarification).
#
. ./common/preamble
_begin_fstest auto nfs quick nfs-conformance

_cleanup()
{
	cd /
	rm -rf $tmp.*
}

. ./common/filter
. ./common/nfs-conformance

_require_test
_require_nfs_conformance_binary op_rename_self

_nfs_conformance_run op_rename_self

status=0
exit
