#!/bin/bash
# SPDX-FileCopyrightText: 2026 Tom Haynes <loghyr@gmail.com>
# SPDX-License-Identifier: BSD-2-Clause OR GPL-2.0-only
#
# FS QA Test No. 944
#
# nfs-conformance: op_read_write_large
#
# large READ/WRITE sizes and offsets (>4 GiB, multi-MiB, unaligned).
#
. ./common/preamble
_begin_fstest auto nfs nfs-conformance

_cleanup()
{
	cd /
	rm -rf $tmp.*
}

. ./common/filter
. ./common/nfs-conformance

_require_test
_require_nfs_conformance_binary op_read_write_large

_nfs_conformance_run op_read_write_large

status=0
exit
