#!/bin/bash
# SPDX-FileCopyrightText: 2026 Tom Haynes <loghyr@gmail.com>
# SPDX-License-Identifier: BSD-2-Clause OR GPL-2.0-only
#
# FS QA Test No. 948
#
# cthon26/nfsv42-tests: op_close_to_open
#
# NFS close-to-open cache consistency.
#
. ./common/preamble
_begin_fstest auto nfs quick cthon26

_cleanup()
{
	cd /
	rm -rf $tmp.*
}

. ./common/filter
. ./common/cthon26

_require_test
_require_cthon26_binary op_close_to_open

_cthon26_run op_close_to_open

status=0
exit
